package com.doguni.model;

public enum Breed {
    AFGHAN_HOUND("Afghan hound"),
    AIREDALE_TERRIER("Airedale terrier"),
    AKITA("Akita"),
    ALASKAN_MALAMUTE("Alaskan malamute"),
    AMERICAN_ENGLISH_COONHOUND("American english coonhound"),
    AMERICAN_FOXHOUND("American foxhound"),
    AMERICAN_STAFFORDSHIRE_TERRIER("American staffordshire terrier"),
    AMERICAN_WATER_SPANIEL("American water spaniel"),
    ANATOLIAN_SHEPHERD_DOG("Anatolian shepherd dog"),
    AUSTRALIAN_CATTLE_DOG("Australian cattle dog"),
    AUSTRALIAN_SHEPHERD("Australian shepherd"),
    AUSTRALIAN_TERRIER("Australian terrier"),
    BASENJI("Basenji"),
    BASSET_HOUND("Basset hound"),
    BEAGLE("Beagle"),
    BEARDED_COLLIE("Bearded collie"),
    BEAUCERON("Beauceron"),
    BEDLINGTON_TERRIER("Bedlington terrier"),
    BELGIAN_MALINOIS("Belgian malinois"),
    BELGIAN_SHEEPDOG("Belgian sheepdog"),
    BELGIAN_TERVUREN("Belgian tervuren"),
    BERGER_PICARD("Berger picard"),
    BERNESE_MOUNTAIN_DOG("Bernese mountain dog"),
    BICHON_FRISÉ("Bichon frise"),
    BLACK_RUSSIAN_TERRIER("Black russian terrier"),
    BLOODHOUND("Bloodhound"),
    BORDER_COLLIE("Border collie"),
    BORDER_TERRIER("Border terrier"),
    BORZOI("Borzoi"),
    BOSTON_TERRIER("Boston terrier"),
    BOUVIER_DES_FLANDRES("Bouvier des flandres"),
    BOXER("Boxer"),
    BOYKIN_SPANIEL("Boykin spaniel"),
    BRIARD("Briard"),
    BRITTANY("Brittany"),
    BRUSSELS_GRIFFON("Brussels griffon"),
    BULL_TERRIER("Bull terrier"),
    BULLDOG("Bulldog"),
    BULLMASTIFF("Bullmastiff"),
    CAIRN_TERRIER("Cairn terrier"),
    CANAAN_DOG("Canaan dog"),
    CANE_CORSO("Cane corso"),
    CARDIGAN_WELSH_CORGI("Cardigan welsh corgi"),
    CAVALIER_KING_CHARLES_SPANIEL("Cavalier king charles spaniel"),
    CHESAPEAKE_BAY_RETRIEVER("Chesapeake bay retriever"),
    CHIHUAHUA("Chihuahua"),
    CHINESE_CRESTED("Chinese crested"),
    CHINESE_SHAR_PEI("Chinese shar-pei"),
    CHOW_CHOW("Chow chow"),
    CLUMBER_SPANIEL("Clumber spaniel"),
    COCKER_SPANIEL("Cocker spaniel"),
    COTON_DE_TULEAR("Coton de tulear"),
    CURLY_COATED_RETRIEVER("Curly-coated retriever"),
    DACHSHUND("Dachshund"),
    DALMATIAN("Dalmatian"),
    DANDIE_DINMONT_TERRIER("Dandie dinmont terrier"),
    DOBERMAN_PINSCHER("Doberman pinscher"),
    DOGO_ARGENTINO("Dogo argentino"),
    DOGUE_DE_BORDEAUX("Dogue de bordeaux"),
    DUTCH_SHEPHERD("Dutch shepherd"),
    ENGLISH_COCKER_SPANIEL("English cocker spaniel"),
    ENGLISH_SETTER("English setter"),
    ENGLISH_SPRINGER_SPANIEL("English springer spaniel"),
    ENTLEBUCHER_MOUNTAIN_DOG("Entlebucher mountain dog"),
    ESTRELA_MOUNTAIN_DOG("Estrela mountain dog"),
    EURASIER("Eurasier"),
    FIELD_SPANIEL("Field spaniel"),
    FINNISH_LAPPHUND("Finnish lapphund"),
    FINNISH_SPITZ("Finnish spitz"),
    FLAT_COATED_RETRIEVER("Flat-coated retriever"),
    FRENCH_BULLDOG("French bulldog"),
    GERMAN_PINSCHER("German pinscher"),
    GERMAN_SHEPHERD_DOG("German shepherd dog"),
    GERMAN_SHORTHAIRED_POINTER("German shorthaired pointer"),
    GERMAN_WIREHAIRED_POINTER("German wirehaired pointer"),
    GIANT_SCHNAUZER("Giant schnauzer"),
    GLEN_OF_IMAAL_TERRIER("Glen of imaal terrier"),
    GOLDEN_RETRIEVER("Golden retriever"),
    GORDON_SETTER("Gordon setter"),
    GRAND_BASSET_GRIFFON_VENDEEN("Grand basset griffon vendeen"),
    GREAT_DANE("Great dane"),
    GREAT_PYRENEES("Great pyrenees"),
    GREATER_SWISS_MOUNTAIN_DOG("Greater swiss mountain dog"),
    GREYHOUND("Greyhound"),
    HAVANESE("Havanese"),
    IBIZAN_HOUND("Ibizan hound"),
    ICELANDIC_SHEEPDOG("Icelandic sheepdog"),
    IRISH_RED_AND_WHITE_SETTER("Irish red and white setter"),
    IRISH_SETTER("Irish setter"),
    IRISH_TERRIER("Irish terrier"),
    IRISH_WATER_SPANIEL("Irish water spaniel"),
    IRISH_WOLFHOUND("Irish wolfhound"),
    ITALIAN_GREYHOUND("Italian greyhound"),
    JAPANESE_CHIN("Japanese chin"),
    KERRY_BLUE_TERRIER("Kerry blue terrier"),
    KEESHOND("Keeshond"),
    KOMONDOR("Komondor"),
    KUVASZ("Kuvasz"),
    LABRADOR_RETRIEVER("Labrador retriever"),
    LAGOTTO_ROMAGNOLO("Lagotto romagnolo"),
    LAKELAND_TERRIER("Lakeland terrier"),
    LEONBERGER("Leonberger"),
    LHASA_APSO("Lhasa apso"),
    LOWCHEN("Lowchen"),
    MALTESE("Maltese"),
    MANCHESTER_TERRIER("Manchester terrier"),
    MASTIFF("Mastiff"),
    MINIATURE_AMERICAN_SHEPHERD("Miniature american shepherd"),
    MINIATURE_BULL_TERRIER("Miniature bull terrier"),
    MINIATURE_SCHNAUZER("Miniature schnauzer"),
    NEAPOLITAN_MASTIFF("Neapolitan mastiff"),
    NEWFOUNDLAND("Newfoundland"),
    NORFOLK_TERRIER("Norfolk terrier"),
    NORWEGIAN_BUHUND("Norwegian buhund"),
    NORWEGIAN_ELKHOUND("Norwegian elkhound"),
    NORWEGIAN_LUNDEHUND("Norwegian lundehund"),
    NORWICH_TERRIER("Norwich terrier"),
    NOVA_SCOTIA_DUCK_TOLLING_RETRIEVER("Nova scotia duck tolling retriever"),
    OLD_ENGLISH_SHEEPDOG("Old english sheepdog"),
    OTTERHOUND("Otterhound"),
    PAPILLON("Papillon"),
    PARSON_RUSSELL_TERRIER("Parson russell terrier"),
    PEKINGESE("Pekingese"),
    PEMBROKE_WELSH_CORGI("Pembroke welsh corgi"),
    PERRO_DE_PRESA_CANARIO("Perro de presa canario"),
    PETIT_BASSET_GRIFFON_VENDEEN("Petit basset griffon vendeen"),
    PHARAOH_HOUND("Pharaoh hound"),
    PLOTT_HOUND("Plott hound"),
    POINTER("Pointer"),
    POLISH_LOWLAND_SHEEPDOG("Polish lowland sheepdog"),
    POMERANIAN("Pomeranian"),
    POODLE("Poodle"),
    PORTUGUESE_WATER_DOG("Portuguese water dog"),
    PUG("Pug"),
    PULI("Puli"),
    PUMI("Pumi"),
    PYRENEAN_SHEPHERD("Pyrenean shepherd"),
    RAT_TERRIER("Rat terrier"),
    REDBONE_COONHOUND("Redbone coonhound"),
    RHODESIAN_RIDGEBACK("Rhodesian ridgeback"),
    ROTTWEILER("Rottweiler"),
    SAINT_BERNARD("Saint bernard"),
    SALUKI("Saluki"),
    SAMOYED("Samoyed"),
    SCHIPPERKE("Schipperke"),
    SCOTTISH_DEERHOUND("Scottish deerhound"),
    SCOTTISH_TERRIER("Scottish terrier"),
    SEALYHAM_TERRIER("Sealyham terrier"),
    SHAR_PEI("Shar pei"),
    SHETLAND_SHEEPDOG("Shetland sheepdog"),
    SHIBA_INU("Shiba inu"),
    SHIH_TZU("Shih tzu"),
    SIBERIAN_HUSKY("Siberian husky"),
    SILKY_TERRIER("Silky terrier"),
    SKYE_TERRIER("Skye terrier"),
    SLOUGHI("Sloughi"),
    SMOOTH_FOX_TERRIER("Smooth fox terrier"),
    SOFT_COATED_WHEATEN_TERRIER("Soft coated wheaten terrier"),
    SUSSEX_SPANIEL("Sussex spaniel"),
    SPANISH_WATER_DOG("Spanish water dog"),
    SPINONE_ITALIANO("Spinone italiano"),
    STAFFORDSHIRE_BULL_TERRIER("Staffordshire bull terrier"),
    STANDARD_SCHNAUZER("Standard schnauzer"),
    SWEDISH_VALLHUND("Swedish vallhund"),
    TIBETAN_MASTIFF("Tibetan mastiff"),
    TIBETAN_TERRIER("Tibetan terrier"),
    TOY_FOX_TERRIER("Toy fox terrier"),
    TREEING_WALKER_COONHOUND("Treeing walker coonhound"),
    VIZSLA("Vizsla"),
    WEIMARANER("Weimaraner"),
    WELSH_SPRINGER_SPANIEL("Welsh springer spaniel"),
    WELSH_TERRIER("Welsh terrier"),
    WEST_HIGHLAND_WHITE_TERRIER("West highland white terrier"),
    WHIPPET("Whippet"),
    WIRE_FOX_TERRIER("Wire fox terrier"),
    WIREHAIRED_POINTING_GRIFFON("Wirehaired pointing griffon"),
    XOLOITZCUINTLI("Xoloitzcuintli"),
    YORKSHIRE_TERRIER("Yorkshire terrier"),
    UNKNOWN("Unknown");

    private final String displayName;

    Breed(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }
}
